import .this_temp_0
import .this_temp_1
import .this_temp_2
import .this_temp_3
import .this_temp_4
import .this_temp_5
import .this_temp_6
import .this_temp_7
import .this_temp_8
import .this_temp_9
import .this_temp_10
import .this_temp_11
import .this_temp_12
import .this_temp_13
import .this_temp_14
import .this_temp_15
import .this_temp_16
import .this_temp_17
import .this_temp_18
import .this_temp_19
import .this_temp_20
import .this_temp_21
import .this_temp_22
import .this_temp_23
import .this_temp_24
import .this_temp_25
import .this_temp_26
import .this_temp_27
import .this_temp_28
import .this_temp_29
import .this_temp_30
import .this_temp_31
import .this_temp_32
import .this_temp_33
import .export_json
open_all_locales